"""Modeller olusturuldu

Revision ID: 1d1b04213947
Revises: 
Create Date: 2026-05-23 16:46:31.986644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1b04213947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitaplar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=128), nullable=False),
    sa.Column('yazar', sa.String(length=128), nullable=False),
    sa.Column('yayin_yili', sa.Integer(), nullable=True),
    sa.Column('eklendigi_tarih', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('incelemeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kitap_id', sa.Integer(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kitap_id'], ['kitaplar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incelemeler')
    op.drop_table('users')
    op.drop_table('kitaplar')
    # ### end Alembic commands ###
